In [1]:
import torch
import numpy as np



In [2]:
num_inputs=2
num_examples=1000
true_w = [2, -3.4]
true_b = 4.2
features=torch.tensor(np.random.normal(0,1,(num_examples,num_inputs)),dtype=torch.float)
features

tensor([[-0.2100, -1.8354],
        [ 0.2628, -1.0058],
        [-1.2729, -0.0047],
        ...,
        [ 1.9593, -0.1982],
        [-0.2812, -1.1316],
        [ 0.2146, -0.2627]])

In [4]:
features.shape
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]+true_b
labels

tensor([ 1.0020e+01,  8.1454e+00,  1.6703e+00,  7.3950e+00,  1.3756e+00,
        -9.6140e-02, -1.8449e+00,  5.5091e+00,  7.7956e+00, -3.0481e+00,
        -1.9549e+00,  1.8317e+00, -3.8641e-01, -9.1684e-01, -8.1745e-01,
         8.4005e+00,  2.7874e+00,  4.1006e+00,  5.2557e+00,  1.0389e+01,
         1.3056e+01,  3.6400e+00,  1.4252e+00,  3.9374e+00,  3.4774e+00,
        -1.6864e-02,  7.4713e+00,  4.4557e+00,  7.3566e+00,  8.3991e+00,
        -3.2930e+00,  2.3368e+00,  4.4339e+00,  4.5114e+00,  2.1027e+00,
         1.6452e+01,  7.8295e+00,  3.6654e+00,  5.6416e+00,  1.0205e+01,
         1.1126e+01,  9.0505e+00,  1.7046e+00,  9.7548e+00,  1.0853e+01,
         1.0223e+01,  7.1769e-01,  3.1446e+00, -1.6881e+00,  1.2855e-01,
        -1.4948e+00,  9.9425e+00,  2.5883e+00,  3.3911e+00,  6.9663e+00,
         3.4731e+00,  6.9534e+00, -1.0450e+00,  9.7745e+00,  1.3426e+00,
        -6.9189e+00,  6.2849e+00,  4.4960e+00, -9.8129e-01,  2.1874e+00,
         9.8453e+00,  2.4498e+00,  5.6333e+00,  1.0

In [5]:
labels.shape



torch.Size([1000])

In [6]:
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)


In [7]:
labels

tensor([ 1.0017e+01,  8.1541e+00,  1.6868e+00,  7.3961e+00,  1.3833e+00,
        -9.3299e-02, -1.8347e+00,  5.5169e+00,  7.7953e+00, -3.0420e+00,
        -1.9410e+00,  1.8278e+00, -3.6860e-01, -9.0573e-01, -8.0550e-01,
         8.4091e+00,  2.7716e+00,  4.0876e+00,  5.2560e+00,  1.0392e+01,
         1.3073e+01,  3.6527e+00,  1.4243e+00,  3.9268e+00,  3.4587e+00,
        -4.4343e-03,  7.4551e+00,  4.4491e+00,  7.3565e+00,  8.3978e+00,
        -3.2891e+00,  2.3411e+00,  4.4219e+00,  4.5203e+00,  2.0954e+00,
         1.6444e+01,  7.8415e+00,  3.6622e+00,  5.6453e+00,  1.0220e+01,
         1.1128e+01,  9.0562e+00,  1.6972e+00,  9.7565e+00,  1.0866e+01,
         1.0230e+01,  7.1528e-01,  3.1516e+00, -1.6841e+00,  1.3175e-01,
        -1.5109e+00,  9.9237e+00,  2.5969e+00,  3.3893e+00,  6.9504e+00,
         3.4755e+00,  6.9334e+00, -1.0467e+00,  9.7730e+00,  1.3387e+00,
        -6.9233e+00,  6.2744e+00,  4.4915e+00, -9.8349e-01,  2.1887e+00,
         9.8454e+00,  2.4565e+00,  5.6331e+00,  1.0

In [8]:
import torch.utils.data as Data
batch_size=10

dataset=Data.TensorDataset(features,labels)

data_iter=Data.DataLoader(dataset,batch_size,shuffle=True)



In [10]:
for x,y in data_iter:
    print(x,y)
    break

tensor([[-1.2780, -1.0636],
        [ 1.4842, -0.4119],
        [ 0.0817,  2.1799],
        [-0.1287, -0.4973],
        [-0.3270,  0.8613],
        [-0.1078,  0.7957],
        [-0.6144, -2.4383],
        [-1.3217,  0.1427],
        [-0.4011, -0.4900],
        [ 0.3166,  0.1507]]) tensor([ 5.2518,  8.5787, -3.0420,  5.6331,  0.6364,  1.2849, 11.2572,  1.0654,
         5.0846,  4.3225])


In [11]:
import torch.nn as nn
class LinearNet(nn.Module):
    def __init__(self,n_features):
        super(LinearNet,self).__init__()
        self.linear=nn.Linear(n_features,1)
    def forward(self,x):
        y=self.linear(x)
        return y
net=LinearNet(num_inputs)
print(net)


LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [12]:
#方法1
net=nn.Sequential(
    nn.Linear(num_inputs,1)
)
#方法2
net=nn.Sequential()
net.add_module('linear',nn.Linear(num_inputs,1))

#方法3
from collections import OrderedDict
net=nn.Sequential(OrderedDict([('linear',nn.Linear(num_inputs,1))]))
print(net)

Sequential(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [13]:
for param in net.parameters():
    print(param)


Parameter containing:
tensor([[-0.5119, -0.6239]], requires_grad=True)
Parameter containing:
tensor([0.3713], requires_grad=True)


In [14]:
#初始化模型参数
from torch.nn import init
init.normal_(net[0].weight,mean=0,std=0.01)
init.constant_(net[0].bias,val=0)


Parameter containing:
tensor([0.], requires_grad=True)

In [15]:
loss=nn.MSELoss()


In [16]:
#优化方法
import torch.optim as optim
optimizer=optim.SGD(net.parameters(),lr=0.03)
print(optimizer)



SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [17]:
num_apochs=3
for epoch in range(1,num_apochs+1):
    for x,y in data_iter:
        output=net(x)
        l=loss(output,y.view(-1,1))
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d, loss: %f' % (epoch, l.item()))


epoch 1, loss: 0.000415
epoch 2, loss: 0.000126
epoch 3, loss: 0.000095


In [18]:
dense=net[0]
print(true_w, dense.weight)
print(true_b, dense.bias)


[2, -3.4] Parameter containing:
tensor([[ 2.0004, -3.4011]], requires_grad=True)
4.2 Parameter containing:
tensor([4.2008], requires_grad=True)


In [ ]:
'''
模块介绍
torch.utils.data模块提供了有关数据处理的工具，
torch.nn模块定义了大量神经网络的层，
torch.nn.init模块定义了各种初始化方法，
torch.optim模块提供了很多常用的优化算法。

'''

