In [1]:
import math
def basic_sigmoid(x):
    s=1/(1+math.exp(-x))
    return s


In [2]:
basic_sigmoid(3)

0.9525741268224334

In [3]:
x=[1,2,3]



In [4]:
basic_sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [6]:
import  numpy as np
x=np.array([1,2,3])
print(np.exp(x))



[ 2.71828183  7.3890561  20.08553692]


In [7]:
x=np.array([1,2,3])
print(x+3)

[4 5 6]


In [8]:
import numpy as np
def sigmoid(x):
    s=1/(1+np.exp((-x)))
    return s 

In [9]:
x=np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [10]:
def sigmoid_derivative(x):
    s=sigmoid(x)
    ds=s*(1-s)
    return ds



In [11]:
x=np.array([1,2,3])
print("sigmoide_derivative(x)="+str(sigmoid_derivative(x)))

sigmoide_derivative(x)=[0.19661193 0.10499359 0.04517666]


In [12]:
def image2vector(image):
    v=image.reshape((image.shape[0]*image.shape[1]*image.shape[2],1))
    return v



In [13]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print('image2vector(image='+str(image2vector(image)))



image2vector(image=[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [14]:
image2vector(image).shape


(18, 1)

In [15]:
x=[[0,3,4],[2,6,4]]
np.linalg.norm(x,axis=1,keepdims=True)


array([[5.        ],
       [7.48331477]])

In [16]:
#归一化
def normalizeRows(x):
    x_norm=np.linalg.norm(x,axis=1,keepdims=True)
    x=x/x_norm
    return x


In [17]:
x=np.array([[0,3,4],[1,6,4]])
print("nomalizerows(x)"+str(normalizeRows(x)))



nomalizerows(x)[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [18]:
def softmax(x):
    x_exp=np.exp(x)
    x_sum=np.linalg.norm(x_exp,axis=1,keepdims=True)
    s=x_exp/x_sum
    return s



In [19]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))



softmax(x) = [[9.99831880e-01 9.11728660e-04 1.83125597e-02 1.23389056e-04
  1.23389056e-04]
 [9.90964875e-01 1.34112512e-01 9.03642998e-04 9.03642998e-04
  9.03642998e-04]]


In [20]:
def L1(yhat,y):
    loss=np.sum(np.abs(y-yhat))
    return loss



In [21]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [22]:
def L2(yhat,y):
    loss=np.dot(y-yhat,y-yhat)
    return loss

In [23]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43
